create table difficulties (
  id int primary key,
  description text
);


create table leaderboard (
  id bigint generated by default as identity primary key,
  name text not null,
  difficulty_id int not null references difficulties (id),
  time int not null,
  data jsonb,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

insert into difficulties (id, description)
values
  (1, 'beginner'),
  (2, 'intermediate'),
  (3, 'expert');

insert into leaderboard (name, difficulty_id, time)
values
  ('john', 1, 12),
  ('jason', 1, 15),
  ('supabase', 1, 7),
  ('gopher', 1, 14),
  ('john', 2, 58),
  ('jason', 2, 98),
  ('foobar', 2, 111),
  ('foobar', 2, 154),
  ('smashing pumps', 3, 154),
  ('john', 3, 304),
  ('gopher', 3, 349),
  ('foobar', 3, 493),
  ('foobar', 3, 348);
