create table difficulties (
  id int primary key,
  description text
);


create table leaderboard (
  id bigint generated by default as identity primary key,
  name text not null,
  difficulty_id int not null references difficulties (id),
  time int not null,
  data jsonb,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

insert into difficulties (id, description)
values
  (1, 'beginner'),
  (2, 'intermediate'),
  (3, 'expert');
